[theme]
#azul
primaryColor="#4FA1F5"
#primaryColor="#d33682"
#backgroundColor="#f0f0f5" fondo blanco
#fondo gris:
backgroundColor="#282A36"
#gris
secondaryBackgroundColor="#44475A"
#secondaryBackgroundColor="#586e75" letras
textColor="#F8F8F2"
font="sans serif"

