[theme]

primaryColor="#3B7B06"
#primaryColor="#d33682"
#backgroundColor="#f0f0f5" blanco
backgroundColor="#282A36"
secondaryBackgroundColor="#44475A"
#secondaryBackgroundColor="#586e75" letras
textColor="#fafafa"
font="sans serif"
